name: Update cable
on:
  schedule:
    - cron:  "55 21 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout My Repo's cable branch
      uses: actions/checkout@v4
      with:
        ref: cable 

    - name: Download M3U from Remote Main Branch and Process
      run: |
        curl -s https://raw.githubusercontent.com/lzh81569/lzh81569.github.io/refs/heads/main/yx.m3u -o cable.m3u
        sed -i 's/192.168.1.3/v6.sucun.top/g' cable.m3u
        sed -i 's/ 4K/4K/g' cable.m3u
        sed -i 's/ HD//g' cable.m3u
        sed -i 's/求索纪实/求索纪录/g' cable.m3u
        sed -i 's/CHC影迷频道/CHC影迷电影/g' cable.m3u
        sed -i 's/\?profile=pass/\?auth=PWgoKtvRUwpwjPsG.U7QbAtatUck\&profile=pass/g' cable.m3u

    - name: Commit and Push changes to My Repo's cable branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add cable.m3u
        git commit -m "1" || echo "No changes to commit"
        git push origin cable
